baseurl = "https://sudo-labs.github.io/r-data-science/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Data Science with R"
theme = "hugo-alabaster-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disqusShortname = ""
googleAnalytics = ""

[params]
	name = "R"
	description = "Analyzing data with R"

	github_user   = "sudo-labs"
	github_repo   = "r-data-science"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"


	github_button  = false
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = false

[params.footer]
	copyright = "[Sudo Labs](https://github.com/sudo-labs)"
	show_powered_by = true

